name: ThreatNet-IRC
version: 0.01
abstract: ThreatNet IRC-specific classes
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
requires:
  perl: 5.005
  Params::Util: 0.01
  ThreatNet::Message: 0.01
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
